### List all messages

GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Message after DI"
}

### Get a particular message
GET http://localhost:3000/messages/88ae6f676c7d3894c06857bb2691574c19595cba